/** @type {import('tailwindcss').Config} */
export default {
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
    theme: {
        extend: {
            colors: {
                'primary-blue': '#537590',
                red: '#FE5B5B',
                'light-green': '#EBFBEC',
                black: '#000000',
                blue: '#0C57A6',
                'gray-light': '#EDF2F7',
                green: '#00A706',
                white: '#FFFFFF',
                'gray-bg': '#F1F5F9',
                'dark-gray': '#595B66',
                'dark-gray-2': '#585757',
                'dark-gray-5': '#525252',
                'light-black': '#262D3B',
                'secondary-blue': '#13456C',
                'steel-blue': '#5C9BCA',
                'royal-blue': '#1D7CE0',
                'bright-blue': '#0076D0',
                'deep-blue': '#325066',
                'charcoal-gray': '#333333',
                'ocean-blue': '#115991',
                'accent-blue': '#29343D',
                'gray-input': '#98A4AE',
                'ice-blue': '#DFE8F0',
                'gold-yellow': '#F4B043',
                'stale-blue': '#5A7297',
                'light-gray': '#E5E5E5',
                'gray-light-5': '#DCDCDC',
                'medium-gray': '#8A8A8A',
                'almost-white': '#F6F7F9',
                'deep-green': '#079455',
                'border-gray': '#D9D9D9',
                cyan: '#A6F7F5',
                'cyan-blue': '#048BF2',
                'dark-blue': '#0A1D3E',
                'gray-light-2': '#F7F8F9CC',
                'gray-light-3': '#8A94AD',
                'yellow-light': '#FFF9DF',
                'blue-light': '#1A62F8',
                'primary-gray': '#E0E0E0',
                'blue-light-2': '#F4F9FC',
                'gray-light-4': '#DFDFDF',
                'red-light': '#D92D20',
                orange: '#FF9743',
                'blue-light-3': '#EDF9FF',
                'sky-blue': '#27A2FF',
                'almost-black': '#292929',
                'green-tag': '#008F4F',
                'dark-navy-blue': '#181D27',
                'blue-light-4': '#A5C3E1',
                'yellow-light-2': '#E4B33314',
                'yellow-light-3': '#FCB708',
                'dark-gray-2': '#191C1F',
                'gray-light-6': '#2F343A',
                'gray-light-7': '#9695951A',
                'gray-light-8': '#D9D9D8',
                'green-light': '#0D8B52',
                'blue-light-2': '#249BF6',
                'deep-yellow': '#FF943E',
                'dark-blue-2': '#0F172A',
                'gray-light-9': '#F3F3F3',
                'blue-light-5': '#E9F5FF',
                'orange-light2': '#E45F07',
                'blue-light-6': '#D0E0EF',
                'blue-light-7': '#008DFF',
                'gray-light-10': '#64748B',
                'gray-light-11': '#80848F',
                'pastel-blue': '#ECF7FF',
                'blue-light-8': '#006BDB',
                'blue-light-9': '#306DDF',
                'black-light': '#141414',
                'blue-light-10': '#EFF4FA',
                'gray-light-12': '#323232',
                'blue-light-11': '#006FE3',
                'green-light-2': '#EBFAF0',
                'green-light-3': '#36C76C',
                'yellow-light-4': '#FFF2D9',
                'yellow-light-5': '#E99B02',
                'red-light-2': '#FF11001A',
                'red-light-3': '#FF1100',
                // Chat colors - Dark theme
                'chat-bg': '#000000',
                'chat-header': '#141414',
                'chat-input-area': '#141414',
                'chat-bubble-user': '#FFFFFF',
                'chat-bubble-admin': '#537590',
                'chat-avatar-bg': '#537590',
                'chat-date-badge': '#333333',
                'chat-time-user': '#8A8A8A',
                'chat-time-admin': '#B0C4D4',
                'chat-input-field': '#292929',
                'chat-send-btn': '#537590',
                'chat-placeholder': '#8A8A8A',
            },
            fontFamily: {
                sans: ['Montserrat', 'system-ui', 'sans-serif'],
                serif: ['Georgia', 'serif'],
                mono: ['Fira Code', 'monospace'],
                montserrat: ['Montserrat', 'sans-serif'],
            },
            fontSize: {
                xs: ['12px', { lineHeight: '16px' }],
                sm: ['14px', { lineHeight: '20px' }],
                sm2: ['15px', { lineHeight: '20px' }],
                base: ['16px', { lineHeight: '24px' }],
                lg: ['18px', { lineHeight: '28px' }],
                xl: ['20px', { lineHeight: '28px' }],
                '2xl': ['24px', { lineHeight: '32px' }],
                '3xl': ['30px', { lineHeight: '36px' }],
                '4xl': ['36px', { lineHeight: '40px' }],
                '5xl': ['48px', { lineHeight: '1' }],
                '6xl': ['60px', { lineHeight: '1' }],
                '7xl': ['72px', { lineHeight: '1' }],
                '8xl': ['96px', { lineHeight: '1' }],
                '9xl': ['128px', { lineHeight: '1' }],
            },
            fontWeight: {
                thin: '100',
                extralight: '200',
                light: '300',
                normal: '400',
                medium: '500',
                semibold: '600',
                bold: '700',
                extrabold: '800',
                black: '900',
            },
            lineHeight: {
                3: '.75rem',
                4: '1rem',
                5: '1.25rem',
                6: '1.5rem',
                7: '1.75rem',
                8: '2rem',
                9: '2.25rem',
                10: '2.5rem',
            },
            letterSpacing: {
                tighter: '-0.05em',
                tight: '-0.025em',
                normal: '0em',
                wide: '0.025em',
                wider: '0.05em',
                widest: '0.1em',
            },
            screens: {
                sm: '640px',
                md: '768px',
                lg: '1024px',
                xl: '1280px',
                '2xl': '1536px',
                'container-sm': '1218px',
                'container-lg': '1440px',
            },
            container: {
                center: true,
                padding: {
                    DEFAULT: '1rem',
                    sm: '2rem',
                    lg: '4rem',
                    xl: '5rem',
                    '2xl': '6rem',
                },
                screens: {
                    sm: '640px',
                    md: '768px',
                    lg: '1024px',
                    xl: '1280px',
                    '2xl': '1536px',
                },
            },
            maxWidth: {
                'container-sm': '1218px',
                'container-lg': '1440px',
            },
        },
    },
    plugins: [],
};
